/** User-facing Chinese UI copy — shared across modules */

export const UI = {
  appName: "Nexa",
  nav: {
    search: "搜索",
    workspace: "工作区",
    create: "创作",
    commerce: "跨境商业",
    guest: "访客",
    account: "账户",
  },
  common: {
    loading: "正在处理…",
    loadingPage: "正在加载…",
    empty: "暂无内容",
    error: "出了点问题",
    retry: "重试",
    save: "保存",
    cancel: "取消",
    confirm: "确认",
    remove: "移除",
    openSource: "打开原文",
    unavailable: "暂未支持",
    comingLater: "后续阶段开放",
    aiUnavailable: "请配置 AI 视频能力或上传素材后再试",
    aiUnavailableDetail: "配置视频生成服务后，即可按分镜自动出画面。",
    providerUnavailable: "服务暂时不可用，请稍后重试",
  },
  search: {
    results: "搜索结果",
    sources: "资料来源",
    addToWorkspace: "+ 加入工作区",
    added: "✓ 已加入",
    noResults: "未找到相关结果，试试换个问法",
  },
  workspace: {
    title: "工作区",
    research: "深入研究",
    researchArea: "研究区域",
    sources: "资料",
    continueSearch: "继续搜索",
    empty: "这个工作区还没有资料",
    aiPlaceholder: "问这些资料，或者告诉 Nexa 你想研究什么……",
    summarize: "总结资料",
    compare: "对比观点",
    extract: "提取要点",
    disagree: "发现分歧",
    createFromSources: "基于资料创作",
    openSource: "打开原文",
  },
  create: {
    title: "创作",
    assets: "素材",
    myAssets: "我的素材",
    imageStudio: "AI 图片生产",
    publish: "发布",
    manageAssets: "管理素材",
    manageSources: "管理来源",
    preview: "预览",
    generateDraft: "AI 生成草稿",
    videoWorkbench: "视频工作台",
    publishUnsupported: "当前平台暂不支持直接发布",
    publishConfirmHint: "请先确认发布预览后再发布。",
    reconnect: "授权已失效，请重新授权连接。",
  },
  publish: {
    title: "发布",
    connections: "平台连接",
    history: "发布记录",
    qaPreview: "质量检查与预览",
    confirm: "确认发布",
  },
  video: {
    planning: "正在规划视频",
    preparingAssets: "正在准备素材",
    generatingShots: "正在生成缺失镜头",
    rendering: "正在剪辑",
    qualityCheck: "正在检查成片",
  },
  commerce: {
    title: "跨境商业",
    overview: "经营概览",
    productDiagnosis: "商品诊断",
    adsDiagnosis: "广告诊断",
    demoNote: "演示数据",
    estimatedProfit: "预计利润",
    inventoryRisk: "库存风险",
  },
  research: {
    conclusion: "研究结论",
    findings: "核心发现",
    evidence: "证据",
    disagreements: "竞争情况",
    trends: "市场趋势",
    risks: "风险",
    opportunities: "机会",
    sources: "来源",
  },
  async: {
    queued: "排队",
    running: "处理中",
    generating: "生成中",
    rendering: "渲染中",
    checking: "检查中",
    completed: "已完成",
    failed: "失败",
  },
  account: {
    title: "账户",
    login: "登录",
    logout: "退出登录",
    credits: "AI Credits",
    connections: "连接中心",
    privacy: "数据与隐私",
    loginRequired: "需要登录后使用",
  },
} as const;
